name: core_moleculenet

datasets:
  - name: esol
    loader: prepared_moleculenet
    dataset_dir: data/eval/moleculenet_sanitized/esol
    eval_split: test
    merge_train_valid: true

  - name: freesolv
    loader: prepared_moleculenet
    dataset_dir: data/eval/moleculenet_sanitized/freesolv
    eval_split: test
    merge_train_valid: true

  - name: lipophilicity
    loader: prepared_moleculenet
    dataset_dir: data/eval/moleculenet_sanitized/lipophilicity
    eval_split: test
    merge_train_valid: true

  - name: bbbp
    loader: prepared_moleculenet
    dataset_dir: data/eval/moleculenet_sanitized/bbbp
    eval_split: test
    merge_train_valid: true

  - name: bace
    loader: prepared_moleculenet
    dataset_dir: data/eval/moleculenet_sanitized/bace
    eval_split: test
    merge_train_valid: true

  - name: clintox
    loader: prepared_moleculenet
    dataset_dir: data/eval/moleculenet_sanitized/clintox
    eval_split: test
    merge_train_valid: true

  - name: tox21
    loader: prepared_moleculenet
    dataset_dir: data/eval/moleculenet_sanitized/tox21
    eval_split: test
    merge_train_valid: true

  - name: sider
    loader: prepared_moleculenet
    dataset_dir: data/eval/moleculenet_sanitized/sider
    eval_split: test
    merge_train_valid: true

  - loader: registered
    name: tdc_herg_blockers
    root: data/eval/tdc_herg_blockers

featurizers:
  - type: ecfp4
    name: ecfp4_2048
    n_bits: 2048
    radius: 2

  - type: modernmolbert_selfies
    name: modernmolbert_pilot
    model_dir: runs/pubchem10m_mps_base_pilot_256/final_model
    tokenizer_path: runs/pubchem10m_mps_base_pilot_256/final_model
    max_seq_length: 256
    pooling: mean
    device: auto
    batch_size: 32

downstream_models:
  classification:
    - name: logistic_balanced
      model_type: logistic_regression
      standardize: true
      params:
        class_weight: balanced
        max_iter: 5000
        C: 1.0

    - name: random_forest_classifier
      model_type: random_forest_classifier
      standardize: false
      params:
        n_estimators: 500
        class_weight: balanced
        min_samples_leaf: 1
        n_jobs: -1

  regression:
    - name: ridge
      model_type: ridge
      standardize: true
      params:
        alpha: 1.0

    - name: random_forest_regressor
      model_type: random_forest_regressor
      standardize: false
      params:
        n_estimators: 500
        min_samples_leaf: 1
        n_jobs: -1

seeds:
  - 13
  - 17
  - 23

eval_split: test
batch_size: 64
use_cache: true
